use abbrevsDB_React;
db.dropDatabase();

db.abbreviations.insertMany([
  { abbrev: "URL", definiton: "Uniform Resource Locator"  },
  { abbrev: "URI", definiton: "Uniform Resource Indentifier"  },
  { abbrev: "URN", definiton: "Uniform Resource Name"  },
  { abbrev: "API", definiton: "Application Programming Interface"  },
  { abbrev: "POP", definiton: "Post Office Protocol"  },
  { abbrev: "IMAP", definiton: "Internet Messaging Access Protocol"  },
  { abbrev: "ERD", definiton: "Entity Relationship Diagram"  },
  { abbrev: "REPL", definiton: "Read Eval Print Loop"  },
  { abbrev: "IoT", definiton: "Internet of Things"  },
  { abbrev: "REST", definiton: "Representational State Transfer"  },
  { abbrev: "ACID", definiton: "Atomic Consistent Isolated Durable"  },
  { abbrev: "DDL", definiton: "Data Definition Language"  },
  { abbrev: "DCL", definiton: "Data Control Language"  },
  { abbrev: "SQL", definiton: "Structured Query Language"  },
  { abbrev: "HTML", definiton: "HyperText Markup Language"  },
  { abbrev: "CMS", definiton: "Content Management System"  },
  { abbrev: "CDN", definiton: "Content Delivery Network"  },
  { abbrev: "CSS", definiton: "Cascading Style Sheets"  },
  { abbrev: "Sass", definiton: "Syntactically Awesome Style Sheets."  },
  { abbrev: "UML", definiton: "Unified Modeling Language"  },
  { abbrev: "ASCII", definiton: "American Standard Code for Information Interchange"  },
  { abbrev: "CES", definiton: "Las Vegas Consumer Electronics Show"  },
  { abbrev: "LAN", definiton: "Local Area Network"  },
  { abbrev: "WAN", definiton: "Wide Area Network"  },
  { abbrev: "POM", definiton: "Project Object Model"  },
  { abbrev: "XML", definiton: "Extensible Markup Language"  },
  { abbrev: "OWASP", definiton: "Open Web Application Security Project"  },
  { abbrev: "ECMA", definiton: "European Computer Manufacturer's Association"  },
  { abbrev: "WWW", definiton: "World Wide Web"  },
  { abbrev: "HTTP", definiton: "HyperText Transfer Protocol"  },
  { abbrev: "HTTPS", definiton: "HyperText Transfer Protocol Secure"  },
  { abbrev: "SSL", definiton: "Secure Socket Layer"  },
  { abbrev: "TLS", definiton: "Transport Layer Security"  },
  { abbrev: "TCP / IP", definiton: "Transmission Control Protocol / Internet Protocol"  },
  { abbrev: "WF / WAF", definiton: "Web Framework / Web Application Framework"  },
  { abbrev: "HATEOAS", definiton: "Hypermedia as the Engine of Application State"  },
  { abbrev: "ALU", definiton: "Arithmetic-Logic Unit"  },
  { abbrev: "CPU", definiton: "Central Processing Unit"  },
  { abbrev: "IRB", definiton: "Interactive Ruby"  },
  { abbrev: "TDD", definiton: "Test Driven Development"  },
  { abbrev: "MVP", definiton: "Minimum Viable Product"  },
  { abbrev: "SMART", definiton: "Specific, Measurable, Achievable (or Attainable), Relevant (or Realistic) and Timely (Timebound)"  },
  { abbrev: "MVC", definiton: "Model View Controller"  },
  { abbrev: "CRUD", definiton: "Create, Read, Update, Delete"  },
  { abbrev: "MSCW", definiton: "Must have, Should have, Could have, and Won't have"  },
  { abbrev: "npm", definiton: "Node Package Manager"  },
  { abbrev: "JSON", definiton: "JavaScript Object Notation"  },
  { abbrev: "CORS", definiton: "Cross-Origin Resource Sharing"  },
  { abbrev: "ORM", definiton: "Object Relational Mapping"  },
  { abbrev: "ODM", definiton: "Object Document Mapping"  },
  { abbrev: "WIMP", definiton: "Windows, Icons, Menus, Pointer"  },
  { abbrev: "GUI", definiton: "Graphical User Interface"  },
  { abbrev: "PPI", definiton: "Pixels Per Inch"  },
  { abbrev: "UTF", definiton: "Unicode Transformation Format"  },
  { abbrev: "GMT", definiton: "Greenwich Mean Time"  },
  { abbrev: "UTC", definiton: "Coordinated Universal Time or Universal Time Coordinated"  },
  { abbrev: "MIME", definiton: "Multipurpose Internet Mail Extensions"  },
  { abbrev: "href", definiton: "Hypertext Reference"  },
  { abbrev: "ARIA", definiton: "Accessible Rich Internet Applications"  },
  { abbrev: "WAI-ARIA", definiton: "Web Accessibility Initiative – Accessible Rich Internet Applications"  },
  { abbrev: "AJAX", definiton: "Asynchronous JavaScript and XML"  },
  { abbrev: "QR code", definiton: "Quick Response code"  },
  { abbrev: "CGI", definiton: "Computer-Generated Imagery"  },
  { abbrev: "blob", definiton: "Binary Large Object"  },
  { abbrev: "MDN", definiton: "Mozilla Developer Network"  },
  { abbrev: "IaaS", definiton: "Infrastructure as a Service"  },
  { abbrev: "PaaS", definiton: "Platform as a Service"  },
  { abbrev: "SaaS", definiton: "Software as a Service"  },
  { abbrev: "IIFE", definiton: "Immediately Invoked Function Expression"  },
  { abbrev: "CLI", definiton: "Command Line Interface"  },
  { abbrev: "BDD", definiton: "Behavioral Driven Development"  },
  { abbrev: "COBOL", definiton: "Common Business Oriented Language"  },
  { abbrev: "ANSI", definiton: "American National Standards Institute"  },
  { abbrev: "GIF", definiton: "Graphics Interchange Format"  },
  { abbrev: "VPN", definiton: "Virtual Private Network"  },
  { abbrev: "Tor", definiton: "The Onion Router"  },
  { abbrev: "CX", definiton: "Customer Experience"  }
]);
