use abbrevsDB_React;
db.dropDatabase();

db.abbreviations.insertMany([
  { abbrev: "URL", definition: "Uniform Resource Locator"  },
  { abbrev: "URI", definition: "Uniform Resource Indentifier"  },
  { abbrev: "URN", definition: "Uniform Resource Name"  },
  { abbrev: "API", definition: "Application Programming Interface"  },
  { abbrev: "POP", definition: "Post Office Protocol"  },
  { abbrev: "IMAP", definition: "Internet Messaging Access Protocol"  },
  { abbrev: "ERD", definition: "Entity Relationship Diagram"  },
  { abbrev: "REPL", definition: "Read Eval Print Loop"  },
  { abbrev: "IoT", definition: "Internet of Things"  },
  { abbrev: "REST", definition: "Representational State Transfer"  },
  { abbrev: "ACID", definition: "Atomic Consistent Isolated Durable"  },
  { abbrev: "DDL", definition: "Data Definition Language"  },
  { abbrev: "DCL", definition: "Data Control Language"  },
  { abbrev: "SQL", definition: "Structured Query Language"  },
  { abbrev: "HTML", definition: "HyperText Markup Language"  },
  { abbrev: "CMS", definition: "Content Management System"  },
  { abbrev: "CDN", definition: "Content Delivery Network"  },
  { abbrev: "CSS", definition: "Cascading Style Sheets"  },
  { abbrev: "Sass", definition: "Syntactically Awesome Style Sheets."  },
  { abbrev: "UML", definition: "Unified Modeling Language"  },
  { abbrev: "ASCII", definition: "American Standard Code for Information Interchange"  },
  { abbrev: "CES", definition: "Las Vegas Consumer Electronics Show"  },
  { abbrev: "LAN", definition: "Local Area Network"  },
  { abbrev: "WAN", definition: "Wide Area Network"  },
  { abbrev: "POM", definition: "Project Object Model"  },
  { abbrev: "XML", definition: "Extensible Markup Language"  },
  { abbrev: "OWASP", definition: "Open Web Application Security Project"  },
  { abbrev: "ECMA", definition: "European Computer Manufacturer's Association"  },
  { abbrev: "WWW", definition: "World Wide Web"  },
  { abbrev: "HTTP", definition: "HyperText Transfer Protocol"  },
  { abbrev: "HTTPS", definition: "HyperText Transfer Protocol Secure"  },
  { abbrev: "SSL", definition: "Secure Socket Layer"  },
  { abbrev: "TLS", definition: "Transport Layer Security"  },
  { abbrev: "TCP / IP", definition: "Transmission Control Protocol / Internet Protocol"  },
  { abbrev: "WF / WAF", definition: "Web Framework / Web Application Framework"  },
  { abbrev: "HATEOAS", definition: "Hypermedia as the Engine of Application State"  },
  { abbrev: "ALU", definition: "Arithmetic-Logic Unit"  },
  { abbrev: "CPU", definition: "Central Processing Unit"  },
  { abbrev: "IRB", definition: "Interactive Ruby"  },
  { abbrev: "TDD", definition: "Test Driven Development"  },
  { abbrev: "MVP", definition: "Minimum Viable Product"  },
  { abbrev: "SMART", definition: "Specific, Measurable, Achievable (or Attainable), Relevant (or Realistic) and Timely (Timebound)"  },
  { abbrev: "MVC", definition: "Model View Controller"  },
  { abbrev: "CRUD", definition: "Create, Read, Update, Delete"  },
  { abbrev: "MSCW", definition: "Must have, Should have, Could have, and Won't have"  },
  { abbrev: "npm", definition: "Node Package Manager"  },
  { abbrev: "JSON", definition: "JavaScript Object Notation"  },
  { abbrev: "CORS", definition: "Cross-Origin Resource Sharing"  },
  { abbrev: "ORM", definition: "Object Relational Mapping"  },
  { abbrev: "ODM", definition: "Object Document Mapping"  },
  { abbrev: "WIMP", definition: "Windows, Icons, Menus, Pointer"  },
  { abbrev: "GUI", definition: "Graphical User Interface"  },
  { abbrev: "PPI", definition: "Pixels Per Inch"  },
  { abbrev: "UTF", definition: "Unicode Transformation Format"  },
  { abbrev: "GMT", definition: "Greenwich Mean Time"  },
  { abbrev: "UTC", definition: "Coordinated Universal Time or Universal Time Coordinated"  },
  { abbrev: "MIME", definition: "Multipurpose Internet Mail Extensions"  },
  { abbrev: "href", definition: "Hypertext Reference"  },
  { abbrev: "ARIA", definition: "Accessible Rich Internet Applications"  },
  { abbrev: "WAI-ARIA", definition: "Web Accessibility Initiative – Accessible Rich Internet Applications"  },
  { abbrev: "AJAX", definition: "Asynchronous JavaScript and XML"  },
  { abbrev: "QR code", definition: "Quick Response code"  },
  { abbrev: "CGI", definition: "Computer-Generated Imagery"  },
  { abbrev: "blob", definition: "Binary Large Object"  },
  { abbrev: "MDN", definition: "Mozilla Developer Network"  },
  { abbrev: "IaaS", definition: "Infrastructure as a Service"  },
  { abbrev: "PaaS", definition: "Platform as a Service"  },
  { abbrev: "SaaS", definition: "Software as a Service"  },
  { abbrev: "IIFE", definition: "Immediately Invoked Function Expression"  },
  { abbrev: "CLI", definition: "Command Line Interface"  },
  { abbrev: "BDD", definition: "Behavioral Driven Development"  },
  { abbrev: "COBOL", definition: "Common Business Oriented Language"  },
  { abbrev: "ANSI", definition: "American National Standards Institute"  },
  { abbrev: "GIF", definition: "Graphics Interchange Format"  },
  { abbrev: "VPN", definition: "Virtual Private Network"  },
  { abbrev: "Tor", definition: "The Onion Router"  },
  { abbrev: "CX", definition: "Customer Experience"  }
]);
